from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_view, name='home'),
    path('vehicles/', views.vehicle_list_view, name='vehicle_list'),
    path('vehicles/<int:vehicle_id>/', views.vehicle_detail_view, name='vehicle_detail'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('add-vehicle/', views.add_vehicle_view, name='add_vehicle'),
    path('booking/<int:vehicle_id>/', views.booking_view, name='booking'),
    path('booking-detail/<int:booking_id>/', views.booking_detail_view, name='booking_detail'),
    path('payment/<int:booking_id>/', views.payment_view, name='payment'),
    path('payment/success/', views.payment_success_view, name='payment_success'),
    path('payment/cancel/', views.payment_cancel_view, name='payment_cancel'),
    # Admin routes
    path('admin-dashboard/', views.admin_dashboard_view, name='admin_dashboard'),
    path('manage/users/', views.admin_users_view, name='admin_users'),
    path('manage/vehicles/', views.admin_vehicles_view, name='admin_vehicles'),
    path('manage/bookings/', views.admin_bookings_view, name='admin_bookings'),
    path('manage/payments/', views.admin_payments_view, name='admin_payments'),
    # Static pages
    path('about-us/', views.about_us_view, name='about_us'),
    path('contact/', views.contact_view, name='contact'),
    path('terms-of-service/', views.terms_of_service_view, name='terms_of_service'),
    path('privacy-policy/', views.privacy_policy_view, name='privacy_policy'),
    # Enhanced features
    path('verify-identity/', views.identity_verification_view, name='identity_verification'),
    path('booking/<int:booking_id>/rate/', views.submit_rating_view, name='submit_rating'),
    path('save-vehicle/<int:vehicle_id>/', views.save_vehicle_view, name='save_vehicle'),
    path('saved-vehicles/', views.saved_vehicles_view, name='saved_vehicles'),
    # New features
    path('booking/<int:booking_id>/refund/', views.request_refund_view, name='request_refund'),
    path('manage/refunds/', views.manage_refunds_view, name='manage_refunds'),
    path('booking/<int:booking_id>/damage/', views.report_damage_view, name='report_damage'),
    path('damage/<int:damage_report_id>/confirm/', views.confirm_damage_view, name='confirm_damage'),
    path('messages/', views.messages_list_view, name='messages_list'),
    path('booking/<int:booking_id>/conversation/', views.conversation_view, name='conversation'),
    path('booking/<int:booking_id>/deposit/', views.security_deposit_view, name='security_deposit'),
    path('api/validate-promo/', views.validate_promo_code_view, name='validate_promo_code'),
    # All 15 New Features
    path('owner/earnings/', views.owner_earnings_view, name='owner_earnings'),
    path('upload-license/', views.upload_drivers_license_view, name='upload_drivers_license'),
    path('manage/licenses/', views.admin_drivers_licenses_view, name='admin_drivers_licenses'),
    path('manage/licenses/<int:license_id>/verify/', views.verify_drivers_license_view, name='verify_drivers_license'),
    path('manage/users/<int:user_id>/blacklist/', views.blacklist_user_view, name='blacklist_user'),
    path('manage/users/<int:user_id>/unblacklist/', views.unblacklist_user_view, name='unblacklist_user'),
    path('booking/<int:booking_id>/sign-agreement/', views.sign_rental_agreement_view, name='sign_rental_agreement'),
    path('compare-vehicles/', views.compare_vehicles_view, name='compare_vehicles'),
    path('request-payout/', views.request_payout_view, name='request_payout'),
    path('manage/payouts/', views.manage_payouts_view, name='manage_payouts'),
    path('manage/utilization/', views.vehicle_utilization_view, name='vehicle_utilization'),
    path('manage/peak-demand/', views.peak_demand_heatmap_view, name='peak_demand_heatmap'),
    path('referral/', views.referral_view, name='referral'),
    path('apply-referral/', views.apply_referral_view, name='apply_referral'),
    path('loyalty-points/', views.loyalty_points_view, name='loyalty_points'),
    path('manage/audit-log/', views.audit_log_view, name='audit_log'),
    path('booking/<int:booking_id>/invoice/', views.generate_invoice_view, name='generate_invoice'),
]
