# Generated by Django 4.2.7 on 2026-05-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_alter_referral_referral_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverslicense',
            name='license_image_front',
            field=models.ImageField(blank=True, null=True, upload_to='drivers_licenses/'),
        ),
    ]
